# Generated by Django 3.1.4 on 2020-12-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20201204_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosepoint',
            name='device_data',
            field=models.JSONField(null=True),
        ),
    ]
