# Generated by Django 3.1.4 on 2020-12-06 00:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20201205_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('high_value', models.IntegerField(default=180)),
                ('low_value', models.IntegerField(default=70)),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.observer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
