# Generated by Django 3.1.4 on 2020-12-07 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alertsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='alerts.observer'),
        ),
        migrations.CreateModel(
            name='GlucoseAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alert_type', models.IntegerField(choices=[(1, 'Low'), (2, 'High')])),
                ('glucose_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.glucosepoint')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='high_alerts', to='alerts.observer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
