# Generated by Django 3.1.4 on 2020-12-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20201207_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsettings',
            name='observer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to='alerts.observer'),
        ),
        migrations.AlterField(
            model_name='observer',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='alerts.uploader'),
        ),
    ]
